// <auto-generated />
using CharleyCompany.Dashboard.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CharleyCompany.Dashboard.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260630021500_AddNotificationRecipients")]
    partial class AddNotificationRecipients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.NotificationRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<System.DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableIMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSms")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnExpenseEvents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnQuoteEvents")
                        .HasColumnType("INTEGER");

                    b.Property<System.DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationRecipients", (string)null);
                });
        }
    }
}
