// <auto-generated />
using System;
using CharleyCompany.Dashboard.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CharleyCompany.Dashboard.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260717012709_AddConsolidatedOperationalEvents")]
    partial class AddConsolidatedOperationalEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.CatalogSyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("SupplyVendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplyVendorId");

                    b.ToTable("CatalogSyncJobs");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PayableInvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("PriceReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("VendorProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PayableInvoiceId");

                    b.HasIndex("VendorProductId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.LocalOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HousecallProLocationId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SalesTaxAccountNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TaxClassification")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HousecallProLocationId")
                        .IsUnique()
                        .HasFilter("\"HousecallProLocationId\" IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("LocalOperations");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.NotificationRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EnableEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableIMessage")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableSms")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnExpenseEvents")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyOnQuoteEvents")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NotificationRecipients");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.OperationIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("LocalOperationId")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("LocalOperationId", "Provider")
                        .IsUnique();

                    b.ToTable("OperationIntegrations");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.OperationalEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExceptionSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("JobNumber")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("LocalOperationId")
                        .HasColumnType("integer");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("QuoteCaseId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("CorrelationId", "Timestamp");

                    b.HasIndex("LocalOperationId", "Timestamp");

                    b.ToTable("OperationalEvents");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PayableInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LocalOperationId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("SupplyVendorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocalOperationId", "JobNumber");

                    b.HasIndex("SupplyVendorId", "InvoiceNumber")
                        .IsUnique();

                    b.ToTable("PayableInvoices");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PriceApprovalRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AutoApproveDollarThreshold")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("AutoApprovePercentThreshold")
                        .HasColumnType("numeric(8,4)");

                    b.Property<bool>("AutoApproveTrustedApiChanges")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("SupplyVendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplyVendorId")
                        .IsUnique();

                    b.ToTable("PriceApprovalRules");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PriceImportDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SupplyVendorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.HasIndex("SupplyVendorId");

                    b.ToTable("PriceImportDocuments");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PriceImportRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<decimal>("MatchConfidence")
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("PriceImportDocumentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProposedUnitPrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("VendorProductId")
                        .HasColumnType("integer");

                    b.Property<string>("VendorSku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PriceImportDocumentId");

                    b.HasIndex("VendorProductId");

                    b.ToTable("PriceImportRows");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Manufacturer", "ManufacturerPartNumber");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteAuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("QuoteCaseId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCaseId");

                    b.ToTable("QuoteAuditEvents");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CompanyCamProjectId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("HousecallProCustomerId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("HousecallProJobId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("HousecallProQuoteId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("LocalOperationId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("HousecallProQuoteId");

                    b.HasIndex("LocalOperationId", "Status");

                    b.ToTable("QuoteCases");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CustomerPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("EquipmentCost")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("LaborHours")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("LaborRate")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MarkupPercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("MaterialUnitCost")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("QuoteVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("WastePercent")
                        .HasColumnType("numeric(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteVersionId");

                    b.ToTable("QuoteLines");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuotePricingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultLaborRate")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("DefaultMarkupPercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("DefaultTaxRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("DefaultWastePercent")
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("LocalOperationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinimumGrossMarginPercent")
                        .HasColumnType("numeric(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("LocalOperationId")
                        .IsUnique();

                    b.ToTable("QuotePricingRules");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteProcessingJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("QuoteCaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCaseId");

                    b.ToTable("QuoteProcessingJobs");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("QuoteCaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCaseId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("QuoteVersions");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.SupplyVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("SupplyVendors");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.UserLocalOperation", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("LocalOperationId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "LocalOperationId");

                    b.HasIndex("LocalOperationId");

                    b.ToTable("UserLocalOperations");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.VendorPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("VendorProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorProductId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("VendorPrices");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.VendorProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PackageQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("PurchaseUnit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SupplyVendorId")
                        .HasColumnType("integer");

                    b.Property<string>("VendorDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("VendorSku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplyVendorId", "VendorSku")
                        .IsUnique();

                    b.ToTable("VendorProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("bytea");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.CatalogSyncJob", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.SupplyVendor", "SupplyVendor")
                        .WithMany("CatalogSyncJobs")
                        .HasForeignKey("SupplyVendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SupplyVendor");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.InvoiceLine", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.PayableInvoice", "PayableInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("PayableInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharleyCompany.Dashboard.Web.Data.VendorProduct", "VendorProduct")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("VendorProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PayableInvoice");

                    b.Navigation("VendorProduct");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.OperationIntegration", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.LocalOperation", "LocalOperation")
                        .WithMany("Integrations")
                        .HasForeignKey("LocalOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalOperation");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.OperationalEvent", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.LocalOperation", "LocalOperation")
                        .WithMany()
                        .HasForeignKey("LocalOperationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LocalOperation");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PayableInvoice", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.LocalOperation", "LocalOperation")
                        .WithMany()
                        .HasForeignKey("LocalOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CharleyCompany.Dashboard.Web.Data.SupplyVendor", "SupplyVendor")
                        .WithMany("PayableInvoices")
                        .HasForeignKey("SupplyVendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalOperation");

                    b.Navigation("SupplyVendor");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PriceApprovalRule", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.SupplyVendor", "SupplyVendor")
                        .WithMany()
                        .HasForeignKey("SupplyVendorId");

                    b.Navigation("SupplyVendor");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PriceImportDocument", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.SupplyVendor", "SupplyVendor")
                        .WithMany("PriceImportDocuments")
                        .HasForeignKey("SupplyVendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SupplyVendor");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PriceImportRow", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.PriceImportDocument", "PriceImportDocument")
                        .WithMany("Rows")
                        .HasForeignKey("PriceImportDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharleyCompany.Dashboard.Web.Data.VendorProduct", "VendorProduct")
                        .WithMany()
                        .HasForeignKey("VendorProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PriceImportDocument");

                    b.Navigation("VendorProduct");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteAuditEvent", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.QuoteCase", "QuoteCase")
                        .WithMany("AuditEvents")
                        .HasForeignKey("QuoteCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteCase");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteCase", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CharleyCompany.Dashboard.Web.Data.LocalOperation", "LocalOperation")
                        .WithMany()
                        .HasForeignKey("LocalOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("LocalOperation");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteLine", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.QuoteVersion", "QuoteVersion")
                        .WithMany("Lines")
                        .HasForeignKey("QuoteVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteVersion");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuotePricingRule", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.LocalOperation", "LocalOperation")
                        .WithMany()
                        .HasForeignKey("LocalOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalOperation");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteProcessingJob", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.QuoteCase", "QuoteCase")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("QuoteCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteCase");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteVersion", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.QuoteCase", "QuoteCase")
                        .WithMany("Versions")
                        .HasForeignKey("QuoteCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteCase");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.UserLocalOperation", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.LocalOperation", "LocalOperation")
                        .WithMany("UserMemberships")
                        .HasForeignKey("LocalOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharleyCompany.Dashboard.Web.Data.ApplicationUser", "User")
                        .WithMany("LocalOperationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalOperation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.VendorPrice", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.VendorProduct", "VendorProduct")
                        .WithMany("Prices")
                        .HasForeignKey("VendorProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorProduct");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.VendorProduct", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.Product", "Product")
                        .WithMany("VendorProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CharleyCompany.Dashboard.Web.Data.SupplyVendor", "SupplyVendor")
                        .WithMany("VendorProducts")
                        .HasForeignKey("SupplyVendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SupplyVendor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CharleyCompany.Dashboard.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CharleyCompany.Dashboard.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.ApplicationUser", b =>
                {
                    b.Navigation("LocalOperationMemberships");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.LocalOperation", b =>
                {
                    b.Navigation("Integrations");

                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PayableInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.PriceImportDocument", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.Product", b =>
                {
                    b.Navigation("VendorProducts");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteCase", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("ProcessingJobs");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.QuoteVersion", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.SupplyVendor", b =>
                {
                    b.Navigation("CatalogSyncJobs");

                    b.Navigation("PayableInvoices");

                    b.Navigation("PriceImportDocuments");

                    b.Navigation("VendorProducts");
                });

            modelBuilder.Entity("CharleyCompany.Dashboard.Web.Data.VendorProduct", b =>
                {
                    b.Navigation("InvoiceLines");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
