CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" character varying(256),
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE TABLE "NotificationRecipients" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DisplayName" character varying(120) NOT NULL,
        "EmailAddress" character varying(256),
        "CellPhoneNumber" character varying(32),
        "EnableEmail" boolean NOT NULL,
        "EnableSms" boolean NOT NULL,
        "EnableIMessage" boolean NOT NULL,
        "NotifyOnQuoteEvents" boolean NOT NULL,
        "NotifyOnExpenseEvents" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_NotificationRecipients" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" character varying(128) NOT NULL,
        "ProviderKey" character varying(128) NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUserPasskeys" (
        "CredentialId" bytea NOT NULL,
        "UserId" text NOT NULL,
        "Data" jsonb NOT NULL,
        CONSTRAINT "PK_AspNetUserPasskeys" PRIMARY KEY ("CredentialId"),
        CONSTRAINT "FK_AspNetUserPasskeys_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" character varying(128) NOT NULL,
        "Name" character varying(128) NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE INDEX "IX_AspNetUserPasskeys_UserId" ON "AspNetUserPasskeys" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260715201843_InitialPostgreSql') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260715201843_InitialPostgreSql', '10.0.9');
    END IF;
END $EF$;
COMMIT;
START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716185130_AddRoleBasedOperations') THEN
    CREATE TABLE "LocalOperations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(120) NOT NULL,
        "Slug" character varying(80) NOT NULL,
        "TimeZone" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LocalOperations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716185130_AddRoleBasedOperations') THEN
    CREATE TABLE "OperationIntegrations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LocalOperationId" integer NOT NULL,
        "Provider" character varying(80) NOT NULL,
        "SecretReference" character varying(300) NOT NULL,
        "ExternalAccountId" character varying(160),
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_OperationIntegrations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OperationIntegrations_LocalOperations_LocalOperationId" FOREIGN KEY ("LocalOperationId") REFERENCES "LocalOperations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716185130_AddRoleBasedOperations') THEN
    CREATE TABLE "UserLocalOperations" (
        "UserId" text NOT NULL,
        "LocalOperationId" integer NOT NULL,
        CONSTRAINT "PK_UserLocalOperations" PRIMARY KEY ("UserId", "LocalOperationId"),
        CONSTRAINT "FK_UserLocalOperations_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserLocalOperations_LocalOperations_LocalOperationId" FOREIGN KEY ("LocalOperationId") REFERENCES "LocalOperations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716185130_AddRoleBasedOperations') THEN
    CREATE UNIQUE INDEX "IX_LocalOperations_Slug" ON "LocalOperations" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716185130_AddRoleBasedOperations') THEN
    CREATE UNIQUE INDEX "IX_OperationIntegrations_LocalOperationId_Provider" ON "OperationIntegrations" ("LocalOperationId", "Provider");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716185130_AddRoleBasedOperations') THEN
    CREATE INDEX "IX_UserLocalOperations_LocalOperationId" ON "UserLocalOperations" ("LocalOperationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716185130_AddRoleBasedOperations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260716185130_AddRoleBasedOperations', '10.0.9');
    END IF;
END $EF$;
COMMIT;
-- End of migration script.
START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "AddressLine1" character varying(160);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "AddressLine2" character varying(160);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "City" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "Country" character varying(80) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "LegalName" character varying(160);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "PostalCode" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "SalesTaxAccountNumber" character varying(80);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "StateOrProvince" character varying(40);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "TaxClassification" character varying(80);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    ALTER TABLE "LocalOperations" ADD "TaxIdentificationNumber" character varying(40);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716192842_AddOperationBusinessDetails') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260716192842_AddOperationBusinessDetails', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716215845_AddSupplyVendorsAndPayableInvoices') THEN
    CREATE TABLE "SupplyVendors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(160) NOT NULL,
        "LegalName" character varying(160),
        "AccountNumber" character varying(80),
        "Email" character varying(256),
        "Phone" character varying(40),
        "AddressLine1" character varying(160),
        "AddressLine2" character varying(160),
        "City" character varying(100),
        "StateOrProvince" character varying(40),
        "PostalCode" character varying(20),
        "Country" character varying(80) NOT NULL,
        "TaxIdentificationNumber" character varying(40),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_SupplyVendors" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716215845_AddSupplyVendorsAndPayableInvoices') THEN
    CREATE TABLE "PayableInvoices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SupplyVendorId" integer NOT NULL,
        "LocalOperationId" integer NOT NULL,
        "InvoiceNumber" character varying(100) NOT NULL,
        "JobNumber" character varying(100) NOT NULL,
        "InvoiceDate" date NOT NULL,
        "DueDate" date NOT NULL,
        "OriginalAmount" numeric(18,2) NOT NULL,
        "AmountPaid" numeric(18,2) NOT NULL,
        "Status" character varying(30) NOT NULL,
        "Notes" character varying(2000),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_PayableInvoices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PayableInvoices_LocalOperations_LocalOperationId" FOREIGN KEY ("LocalOperationId") REFERENCES "LocalOperations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PayableInvoices_SupplyVendors_SupplyVendorId" FOREIGN KEY ("SupplyVendorId") REFERENCES "SupplyVendors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716215845_AddSupplyVendorsAndPayableInvoices') THEN
    CREATE INDEX "IX_PayableInvoices_LocalOperationId_JobNumber" ON "PayableInvoices" ("LocalOperationId", "JobNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716215845_AddSupplyVendorsAndPayableInvoices') THEN
    CREATE UNIQUE INDEX "IX_PayableInvoices_SupplyVendorId_InvoiceNumber" ON "PayableInvoices" ("SupplyVendorId", "InvoiceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716215845_AddSupplyVendorsAndPayableInvoices') THEN
    CREATE INDEX "IX_SupplyVendors_Name" ON "SupplyVendors" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716215845_AddSupplyVendorsAndPayableInvoices') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260716215845_AddSupplyVendorsAndPayableInvoices', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716232318_AddHousecallProOperationId') THEN
    ALTER TABLE "LocalOperations" ADD "HousecallProLocationId" character varying(160);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716232318_AddHousecallProOperationId') THEN
    CREATE UNIQUE INDEX "IX_LocalOperations_HousecallProLocationId" ON "LocalOperations" ("HousecallProLocationId") WHERE "HousecallProLocationId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260716232318_AddHousecallProOperationId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260716232318_AddHousecallProOperationId', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(160) NOT NULL,
        "Category" character varying(100),
        "Manufacturer" character varying(120),
        "ManufacturerPartNumber" character varying(100),
        "UnitOfMeasure" character varying(40) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE TABLE "VendorProducts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SupplyVendorId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "VendorSku" character varying(100) NOT NULL,
        "VendorDescription" character varying(300),
        "PackageQuantity" numeric(18,4) NOT NULL,
        "PurchaseUnit" character varying(40) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_VendorProducts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VendorProducts_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_VendorProducts_SupplyVendors_SupplyVendorId" FOREIGN KEY ("SupplyVendorId") REFERENCES "SupplyVendors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE TABLE "InvoiceLines" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PayableInvoiceId" integer NOT NULL,
        "VendorProductId" integer NOT NULL,
        "Quantity" numeric(18,4) NOT NULL,
        "UnitPrice" numeric(18,4) NOT NULL,
        "LineTotal" numeric(18,2) NOT NULL,
        "PriceReviewStatus" character varying(30) NOT NULL,
        "Notes" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_InvoiceLines" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InvoiceLines_PayableInvoices_PayableInvoiceId" FOREIGN KEY ("PayableInvoiceId") REFERENCES "PayableInvoices" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_InvoiceLines_VendorProducts_VendorProductId" FOREIGN KEY ("VendorProductId") REFERENCES "VendorProducts" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE TABLE "VendorPrices" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VendorProductId" integer NOT NULL,
        "UnitPrice" numeric(18,4) NOT NULL,
        "EffectiveDate" date NOT NULL,
        "ExpirationDate" date,
        "SourceType" character varying(30) NOT NULL,
        "SourceReference" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VendorPrices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VendorPrices_VendorProducts_VendorProductId" FOREIGN KEY ("VendorProductId") REFERENCES "VendorProducts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE INDEX "IX_InvoiceLines_PayableInvoiceId" ON "InvoiceLines" ("PayableInvoiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE INDEX "IX_InvoiceLines_VendorProductId" ON "InvoiceLines" ("VendorProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE INDEX "IX_Products_Manufacturer_ManufacturerPartNumber" ON "Products" ("Manufacturer", "ManufacturerPartNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE UNIQUE INDEX "IX_VendorPrices_VendorProductId_EffectiveDate" ON "VendorPrices" ("VendorProductId", "EffectiveDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE INDEX "IX_VendorProducts_ProductId" ON "VendorProducts" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    CREATE UNIQUE INDEX "IX_VendorProducts_SupplyVendorId_VendorSku" ON "VendorProducts" ("SupplyVendorId", "VendorSku");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717003649_AddVendorCatalogAndInvoiceLines') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260717003649_AddVendorCatalogAndInvoiceLines', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE TABLE "CatalogSyncJobs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SupplyVendorId" integer NOT NULL,
        "Provider" character varying(80) NOT NULL,
        "Status" character varying(30) NOT NULL,
        "Message" character varying(500),
        "RequestedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_CatalogSyncJobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CatalogSyncJobs_SupplyVendors_SupplyVendorId" FOREIGN KEY ("SupplyVendorId") REFERENCES "SupplyVendors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE TABLE "PriceApprovalRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SupplyVendorId" integer,
        "AutoApprovePercentThreshold" numeric(8,4) NOT NULL,
        "AutoApproveDollarThreshold" numeric(18,4) NOT NULL,
        "AutoApproveTrustedApiChanges" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_PriceApprovalRules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PriceApprovalRules_SupplyVendors_SupplyVendorId" FOREIGN KEY ("SupplyVendorId") REFERENCES "SupplyVendors" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE TABLE "PriceImportDocuments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SupplyVendorId" integer NOT NULL,
        "OriginalFileName" character varying(260) NOT NULL,
        "StoragePath" character varying(500) NOT NULL,
        "Sha256" character varying(64) NOT NULL,
        "ContentType" character varying(100) NOT NULL,
        "Status" character varying(40) NOT NULL,
        "UploadedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PriceImportDocuments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PriceImportDocuments_SupplyVendors_SupplyVendorId" FOREIGN KEY ("SupplyVendorId") REFERENCES "SupplyVendors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE TABLE "PriceImportRows" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PriceImportDocumentId" integer NOT NULL,
        "VendorProductId" integer,
        "VendorSku" character varying(100) NOT NULL,
        "Description" character varying(300) NOT NULL,
        "ProposedUnitPrice" numeric(18,4) NOT NULL,
        "EffectiveDate" date NOT NULL,
        "MatchConfidence" numeric(5,4) NOT NULL,
        "ReviewStatus" character varying(30) NOT NULL,
        CONSTRAINT "PK_PriceImportRows" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PriceImportRows_PriceImportDocuments_PriceImportDocumentId" FOREIGN KEY ("PriceImportDocumentId") REFERENCES "PriceImportDocuments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PriceImportRows_VendorProducts_VendorProductId" FOREIGN KEY ("VendorProductId") REFERENCES "VendorProducts" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE INDEX "IX_CatalogSyncJobs_SupplyVendorId" ON "CatalogSyncJobs" ("SupplyVendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE UNIQUE INDEX "IX_PriceApprovalRules_SupplyVendorId" ON "PriceApprovalRules" ("SupplyVendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE UNIQUE INDEX "IX_PriceImportDocuments_Sha256" ON "PriceImportDocuments" ("Sha256");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE INDEX "IX_PriceImportDocuments_SupplyVendorId" ON "PriceImportDocuments" ("SupplyVendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE INDEX "IX_PriceImportRows_PriceImportDocumentId" ON "PriceImportRows" ("PriceImportDocumentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    CREATE INDEX "IX_PriceImportRows_VendorProductId" ON "PriceImportRows" ("VendorProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717004735_AddCatalogImportAutomation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260717004735_AddCatalogImportAutomation', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE TABLE "QuoteCases" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LocalOperationId" integer NOT NULL,
        "HousecallProQuoteId" character varying(160),
        "HousecallProJobId" character varying(160),
        "HousecallProCustomerId" character varying(160),
        "CompanyCamProjectId" character varying(160),
        "CustomerName" character varying(160),
        "CustomerEmail" character varying(256),
        "WorkDescription" character varying(2000) NOT NULL,
        "Status" character varying(40) NOT NULL,
        "AssignedUserId" character varying(450),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_QuoteCases" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteCases_AspNetUsers_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_QuoteCases_LocalOperations_LocalOperationId" FOREIGN KEY ("LocalOperationId") REFERENCES "LocalOperations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE TABLE "QuotePricingRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LocalOperationId" integer NOT NULL,
        "DefaultLaborRate" numeric(18,4) NOT NULL,
        "DefaultMarkupPercent" numeric(8,4) NOT NULL,
        "DefaultWastePercent" numeric(8,4) NOT NULL,
        "DefaultTaxRate" numeric(8,4) NOT NULL,
        "MinimumGrossMarginPercent" numeric(8,4) NOT NULL,
        CONSTRAINT "PK_QuotePricingRules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuotePricingRules_LocalOperations_LocalOperationId" FOREIGN KEY ("LocalOperationId") REFERENCES "LocalOperations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE TABLE "QuoteAuditEvents" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteCaseId" integer NOT NULL,
        "PreviousStatus" character varying(40) NOT NULL,
        "NewStatus" character varying(40) NOT NULL,
        "UserId" character varying(450),
        "Explanation" character varying(1000),
        "OccurredAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_QuoteAuditEvents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteAuditEvents_QuoteCases_QuoteCaseId" FOREIGN KEY ("QuoteCaseId") REFERENCES "QuoteCases" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE TABLE "QuoteProcessingJobs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteCaseId" integer NOT NULL,
        "JobType" character varying(60) NOT NULL,
        "Status" character varying(30) NOT NULL,
        "Message" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_QuoteProcessingJobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteProcessingJobs_QuoteCases_QuoteCaseId" FOREIGN KEY ("QuoteCaseId") REFERENCES "QuoteCases" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE TABLE "QuoteVersions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteCaseId" integer NOT NULL,
        "VersionNumber" integer NOT NULL,
        "Status" character varying(30) NOT NULL,
        "TaxRate" numeric(8,4) NOT NULL,
        "DiscountAmount" numeric(18,2) NOT NULL,
        "CustomerNotes" character varying(2000),
        "ApprovedByUserId" character varying(450),
        "ApprovedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_QuoteVersions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteVersions_QuoteCases_QuoteCaseId" FOREIGN KEY ("QuoteCaseId") REFERENCES "QuoteCases" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE TABLE "QuoteLines" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteVersionId" integer NOT NULL,
        "SortOrder" integer NOT NULL,
        "Description" character varying(500) NOT NULL,
        "Quantity" numeric(18,4) NOT NULL,
        "Unit" character varying(40) NOT NULL,
        "MaterialUnitCost" numeric(18,4) NOT NULL,
        "LaborHours" numeric(18,4) NOT NULL,
        "LaborRate" numeric(18,4) NOT NULL,
        "EquipmentCost" numeric(18,2) NOT NULL,
        "WastePercent" numeric(8,4) NOT NULL,
        "MarkupPercent" numeric(8,4) NOT NULL,
        "CustomerPrice" numeric(18,2) NOT NULL,
        "Source" character varying(100) NOT NULL,
        CONSTRAINT "PK_QuoteLines" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteLines_QuoteVersions_QuoteVersionId" FOREIGN KEY ("QuoteVersionId") REFERENCES "QuoteVersions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE INDEX "IX_QuoteAuditEvents_QuoteCaseId" ON "QuoteAuditEvents" ("QuoteCaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE INDEX "IX_QuoteCases_AssignedUserId" ON "QuoteCases" ("AssignedUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE INDEX "IX_QuoteCases_HousecallProQuoteId" ON "QuoteCases" ("HousecallProQuoteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE INDEX "IX_QuoteCases_LocalOperationId_Status" ON "QuoteCases" ("LocalOperationId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE INDEX "IX_QuoteLines_QuoteVersionId" ON "QuoteLines" ("QuoteVersionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE UNIQUE INDEX "IX_QuotePricingRules_LocalOperationId" ON "QuotePricingRules" ("LocalOperationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE INDEX "IX_QuoteProcessingJobs_QuoteCaseId" ON "QuoteProcessingJobs" ("QuoteCaseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    CREATE UNIQUE INDEX "IX_QuoteVersions_QuoteCaseId_VersionNumber" ON "QuoteVersions" ("QuoteCaseId", "VersionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717011206_AddOperationQuotingFramework') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260717011206_AddOperationQuotingFramework', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717012709_AddConsolidatedOperationalEvents') THEN
    CREATE TABLE "OperationalEvents" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EventId" uuid NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "Severity" character varying(20) NOT NULL,
        "Environment" character varying(40) NOT NULL,
        "Machine" character varying(120) NOT NULL,
        "Service" character varying(120) NOT NULL,
        "Module" character varying(120) NOT NULL,
        "LocalOperationId" integer,
        "CorrelationId" character varying(100) NOT NULL,
        "QuoteCaseId" integer,
        "JobNumber" character varying(160),
        "Step" character varying(120) NOT NULL,
        "Status" character varying(30) NOT NULL,
        "DurationMilliseconds" bigint,
        "Message" character varying(2000) NOT NULL,
        "ErrorCode" character varying(100),
        "ExceptionSummary" character varying(4000),
        "MetadataJson" character varying(4000),
        "ReceivedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_OperationalEvents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OperationalEvents_LocalOperations_LocalOperationId" FOREIGN KEY ("LocalOperationId") REFERENCES "LocalOperations" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717012709_AddConsolidatedOperationalEvents') THEN
    CREATE INDEX "IX_OperationalEvents_CorrelationId_Timestamp" ON "OperationalEvents" ("CorrelationId", "Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717012709_AddConsolidatedOperationalEvents') THEN
    CREATE UNIQUE INDEX "IX_OperationalEvents_EventId" ON "OperationalEvents" ("EventId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717012709_AddConsolidatedOperationalEvents') THEN
    CREATE INDEX "IX_OperationalEvents_LocalOperationId_Timestamp" ON "OperationalEvents" ("LocalOperationId", "Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717012709_AddConsolidatedOperationalEvents') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260717012709_AddConsolidatedOperationalEvents', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717162932_AddMustChangePassword') THEN
    ALTER TABLE "AspNetUsers" ADD "MustChangePassword" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260717162932_AddMustChangePassword') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260717162932_AddMustChangePassword', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723173606_AddHousecallProRecordCache') THEN
    CREATE TABLE "HousecallProEstimates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LocalOperationId" integer NOT NULL,
        "ExternalId" character varying(160) NOT NULL,
        "EstimateNumber" character varying(100),
        "CustomerName" character varying(200),
        "Status" character varying(80),
        "ApprovalStatus" character varying(80),
        "TotalAmount" numeric(18,2) NOT NULL,
        "SourceUpdatedAt" timestamp with time zone,
        "LastSyncedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HousecallProEstimates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HousecallProEstimates_LocalOperations_LocalOperationId" FOREIGN KEY ("LocalOperationId") REFERENCES "LocalOperations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723173606_AddHousecallProRecordCache') THEN
    CREATE TABLE "HousecallProJobs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LocalOperationId" integer NOT NULL,
        "ExternalId" character varying(160) NOT NULL,
        "JobNumber" character varying(100),
        "CustomerName" character varying(200),
        "WorkStatus" character varying(80),
        "Address" character varying(300),
        "ScheduledStart" timestamp with time zone,
        "ScheduledEnd" timestamp with time zone,
        "TotalAmount" numeric(18,2) NOT NULL,
        "SourceUpdatedAt" timestamp with time zone,
        "LastSyncedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HousecallProJobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HousecallProJobs_LocalOperations_LocalOperationId" FOREIGN KEY ("LocalOperationId") REFERENCES "LocalOperations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723173606_AddHousecallProRecordCache') THEN
    CREATE UNIQUE INDEX "IX_HousecallProEstimates_LocalOperationId_ExternalId" ON "HousecallProEstimates" ("LocalOperationId", "ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723173606_AddHousecallProRecordCache') THEN
    CREATE INDEX "IX_HousecallProEstimates_LocalOperationId_Status" ON "HousecallProEstimates" ("LocalOperationId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723173606_AddHousecallProRecordCache') THEN
    CREATE UNIQUE INDEX "IX_HousecallProJobs_LocalOperationId_ExternalId" ON "HousecallProJobs" ("LocalOperationId", "ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723173606_AddHousecallProRecordCache') THEN
    CREATE INDEX "IX_HousecallProJobs_LocalOperationId_WorkStatus" ON "HousecallProJobs" ("LocalOperationId", "WorkStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723173606_AddHousecallProRecordCache') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723173606_AddHousecallProRecordCache', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723181615_AddHousecallProEstimateContactDetails') THEN
    ALTER TABLE "HousecallProEstimates" ADD "CustomerAddress" character varying(400);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723181615_AddHousecallProEstimateContactDetails') THEN
    ALTER TABLE "HousecallProEstimates" ADD "CustomerEmail" character varying(256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723181615_AddHousecallProEstimateContactDetails') THEN
    ALTER TABLE "HousecallProEstimates" ADD "CustomerPhone" character varying(40);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723181615_AddHousecallProEstimateContactDetails') THEN
    ALTER TABLE "HousecallProEstimates" ADD "ExpiresAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723181615_AddHousecallProEstimateContactDetails') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723181615_AddHousecallProEstimateContactDetails', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723213108_AddHousecallProEstimateDate') THEN
    ALTER TABLE "HousecallProEstimates" ADD "EstimateDate" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723213108_AddHousecallProEstimateDate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723213108_AddHousecallProEstimateDate', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220207_AddHousecallProEstimateWorkflow') THEN
    ALTER TABLE "HousecallProEstimates" ADD "CreatedByName" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220207_AddHousecallProEstimateWorkflow') THEN
    ALTER TABLE "HousecallProEstimates" ADD "InternalStatus" character varying(80) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220207_AddHousecallProEstimateWorkflow') THEN
    ALTER TABLE "HousecallProEstimates" ADD "InternalStatusNote" character varying(450);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220207_AddHousecallProEstimateWorkflow') THEN
    ALTER TABLE "HousecallProEstimates" ADD "InternalStatusUpdatedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220207_AddHousecallProEstimateWorkflow') THEN
    ALTER TABLE "HousecallProEstimates" ADD "InternalStatusUpdatedBy" character varying(450);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220207_AddHousecallProEstimateWorkflow') THEN
    CREATE TABLE "HousecallProEstimateCommunications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "HousecallProEstimateId" integer NOT NULL,
        "CommunicationType" character varying(40) NOT NULL,
        "Direction" character varying(40) NOT NULL,
        "Notes" character varying(4000) NOT NULL,
        "EnteredByUserId" character varying(450),
        "EnteredByName" character varying(450) NOT NULL,
        "EnteredAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HousecallProEstimateCommunications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HousecallProEstimateCommunications_HousecallProEstimates_Ho~" FOREIGN KEY ("HousecallProEstimateId") REFERENCES "HousecallProEstimates" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220207_AddHousecallProEstimateWorkflow') THEN
    CREATE INDEX "IX_HousecallProEstimateCommunications_HousecallProEstimateId_E~" ON "HousecallProEstimateCommunications" ("HousecallProEstimateId", "EnteredAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220207_AddHousecallProEstimateWorkflow') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723220207_AddHousecallProEstimateWorkflow', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220333_NormalizeHousecallProEstimateStatuses') THEN
    UPDATE "HousecallProEstimates"
    SET "InternalStatus" = 'New'
    WHERE "InternalStatus" IS NULL OR btrim("InternalStatus") = '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220333_NormalizeHousecallProEstimateStatuses') THEN
    ALTER TABLE "HousecallProEstimates" ALTER COLUMN "InternalStatus" SET DEFAULT 'New';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723220333_NormalizeHousecallProEstimateStatuses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723220333_NormalizeHousecallProEstimateStatuses', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723222221_ConsolidateHousecallProEstimateStatus') THEN
    ALTER TABLE "HousecallProEstimates" ALTER COLUMN "InternalStatus" DROP NOT NULL;
    ALTER TABLE "HousecallProEstimates" ALTER COLUMN "InternalStatus" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723222221_ConsolidateHousecallProEstimateStatus') THEN
    UPDATE "HousecallProEstimates"
    SET "InternalStatus" = NULL
    WHERE "InternalStatus" = 'New';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723222221_ConsolidateHousecallProEstimateStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723222221_ConsolidateHousecallProEstimateStatus', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723224740_AddHousecallProEstimateFollowUpHistory') THEN
    CREATE TABLE "HousecallProEstimateFollowUps" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "HousecallProEstimateId" integer NOT NULL,
        "Status" character varying(80) NOT NULL,
        "Notes" character varying(2000) NOT NULL,
        "EnteredByUserId" character varying(450),
        "EnteredByName" character varying(450) NOT NULL,
        "EnteredAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HousecallProEstimateFollowUps" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HousecallProEstimateFollowUps_HousecallProEstimates_Houseca~" FOREIGN KEY ("HousecallProEstimateId") REFERENCES "HousecallProEstimates" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723224740_AddHousecallProEstimateFollowUpHistory') THEN
    CREATE INDEX "IX_HousecallProEstimateFollowUps_HousecallProEstimateId_Entere~" ON "HousecallProEstimateFollowUps" ("HousecallProEstimateId", "EnteredAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260723224740_AddHousecallProEstimateFollowUpHistory') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260723224740_AddHousecallProEstimateFollowUpHistory', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724200532_ExpandHousecallProJobSummaries') THEN
    ALTER TABLE "HousecallProJobs" ALTER COLUMN "Address" TYPE character varying(400);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724200532_ExpandHousecallProJobSummaries') THEN
    ALTER TABLE "HousecallProJobs" ADD "CreatedByName" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724200532_ExpandHousecallProJobSummaries') THEN
    ALTER TABLE "HousecallProJobs" ADD "CustomerEmail" character varying(256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724200532_ExpandHousecallProJobSummaries') THEN
    ALTER TABLE "HousecallProJobs" ADD "CustomerPhone" character varying(40);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724200532_ExpandHousecallProJobSummaries') THEN
    ALTER TABLE "HousecallProJobs" ADD "JobPrice" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724200532_ExpandHousecallProJobSummaries') THEN
    ALTER TABLE "HousecallProJobs" ADD "OutstandingBalance" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260724200532_ExpandHousecallProJobSummaries') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260724200532_ExpandHousecallProJobSummaries', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725195210_AddHousecallProJobFollowUpWorkflow') THEN
    ALTER TABLE "HousecallProJobs" ADD "InternalStatus" character varying(80);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725195210_AddHousecallProJobFollowUpWorkflow') THEN
    ALTER TABLE "HousecallProJobs" ADD "InternalStatusNote" character varying(450);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725195210_AddHousecallProJobFollowUpWorkflow') THEN
    ALTER TABLE "HousecallProJobs" ADD "InternalStatusUpdatedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725195210_AddHousecallProJobFollowUpWorkflow') THEN
    ALTER TABLE "HousecallProJobs" ADD "InternalStatusUpdatedBy" character varying(450);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725195210_AddHousecallProJobFollowUpWorkflow') THEN
    CREATE TABLE "HousecallProJobFollowUps" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "HousecallProJobId" integer NOT NULL,
        "Status" character varying(80) NOT NULL,
        "Notes" character varying(2000) NOT NULL,
        "EnteredByUserId" character varying(450),
        "EnteredByName" character varying(450) NOT NULL,
        "EnteredAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HousecallProJobFollowUps" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HousecallProJobFollowUps_HousecallProJobs_HousecallProJobId" FOREIGN KEY ("HousecallProJobId") REFERENCES "HousecallProJobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725195210_AddHousecallProJobFollowUpWorkflow') THEN
    CREATE INDEX "IX_HousecallProJobs_LocalOperationId_InternalStatus" ON "HousecallProJobs" ("LocalOperationId", "InternalStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725195210_AddHousecallProJobFollowUpWorkflow') THEN
    CREATE INDEX "IX_HousecallProJobFollowUps_HousecallProJobId_EnteredAt" ON "HousecallProJobFollowUps" ("HousecallProJobId", "EnteredAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260725195210_AddHousecallProJobFollowUpWorkflow') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260725195210_AddHousecallProJobFollowUpWorkflow', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726110804_AddEstimateStartCustomerAddress') THEN
    ALTER TABLE "QuoteCases" ADD "CustomerAddress" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726110804_AddEstimateStartCustomerAddress') THEN
    ALTER TABLE "QuoteCases" ADD "HousecallProEstimateNumber" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726110804_AddEstimateStartCustomerAddress') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260726110804_AddEstimateStartCustomerAddress', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726121049_AddEstimateProjectTasks') THEN
    CREATE TABLE "QuoteProjectTasks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteCaseId" integer NOT NULL,
        "SortOrder" integer NOT NULL,
        "TaskType" character varying(100) NOT NULL,
        "ScopeOfWork" character varying(4000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_QuoteProjectTasks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteProjectTasks_QuoteCases_QuoteCaseId" FOREIGN KEY ("QuoteCaseId") REFERENCES "QuoteCases" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726121049_AddEstimateProjectTasks') THEN
    CREATE TABLE "QuoteProjectTaskPhotos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteProjectTaskId" integer NOT NULL,
        "OriginalFileName" character varying(255) NOT NULL,
        "StoragePath" character varying(500) NOT NULL,
        "ContentType" character varying(100) NOT NULL,
        "FileSize" bigint NOT NULL,
        "CapturedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_QuoteProjectTaskPhotos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteProjectTaskPhotos_QuoteProjectTasks_QuoteProjectTaskId" FOREIGN KEY ("QuoteProjectTaskId") REFERENCES "QuoteProjectTasks" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726121049_AddEstimateProjectTasks') THEN
    CREATE INDEX "IX_QuoteProjectTaskPhotos_QuoteProjectTaskId_CapturedAt" ON "QuoteProjectTaskPhotos" ("QuoteProjectTaskId", "CapturedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726121049_AddEstimateProjectTasks') THEN
    CREATE UNIQUE INDEX "IX_QuoteProjectTasks_QuoteCaseId_SortOrder" ON "QuoteProjectTasks" ("QuoteCaseId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726121049_AddEstimateProjectTasks') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260726121049_AddEstimateProjectTasks', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    ALTER TABLE "QuoteProjectTaskPhotos" ADD "RequirementKey" character varying(80) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    ALTER TABLE "QuoteProjectTaskPhotos" ADD "RequirementLabel" character varying(160) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    ALTER TABLE "QuoteProcessingJobs" ADD "QuoteProjectTaskId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    CREATE TABLE "CentComChatSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "CreatedByUserId" character varying(450) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CentComChatSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CentComChatSessions_AspNetUsers_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    CREATE TABLE "CentComChatMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CentComChatSessionId" integer NOT NULL,
        "Role" character varying(20) NOT NULL,
        "Content" character varying(12000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CentComChatMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CentComChatMessages_CentComChatSessions_CentComChatSessionId" FOREIGN KEY ("CentComChatSessionId") REFERENCES "CentComChatSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    CREATE INDEX "IX_QuoteProcessingJobs_QuoteProjectTaskId" ON "QuoteProcessingJobs" ("QuoteProjectTaskId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    CREATE INDEX "IX_CentComChatMessages_CentComChatSessionId_CreatedAt" ON "CentComChatMessages" ("CentComChatSessionId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    CREATE INDEX "IX_CentComChatSessions_CreatedByUserId_UpdatedAt" ON "CentComChatSessions" ("CreatedByUserId", "UpdatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    ALTER TABLE "QuoteProcessingJobs" ADD CONSTRAINT "FK_QuoteProcessingJobs_QuoteProjectTasks_QuoteProjectTaskId" FOREIGN KEY ("QuoteProjectTaskId") REFERENCES "QuoteProjectTasks" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260726123954_AddCentComTaskSubmissionAndChat') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260726123954_AddCentComTaskSubmissionAndChat', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729163041_AddCentComTaskAnalysis') THEN
    CREATE TABLE "QuoteTaskAnalyses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteProjectTaskId" integer NOT NULL,
        "RevisionNumber" integer NOT NULL,
        "Status" character varying(30) NOT NULL,
        "SubmittedByUserId" character varying(450),
        "ModelVersion" character varying(120),
        "Assumptions" character varying(4000),
        "QuestionsAndWarnings" character varying(4000),
        "DeliveryAllowance" numeric(18,2) NOT NULL,
        "TaxAllowance" numeric(18,2) NOT NULL,
        "OtherAllowance" numeric(18,2) NOT NULL,
        "SubmittedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "ReviewedAt" timestamp with time zone,
        "ReviewedByUserId" character varying(450),
        CONSTRAINT "PK_QuoteTaskAnalyses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteTaskAnalyses_QuoteProjectTasks_QuoteProjectTaskId" FOREIGN KEY ("QuoteProjectTaskId") REFERENCES "QuoteProjectTasks" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729163041_AddCentComTaskAnalysis') THEN
    CREATE TABLE "QuoteTaskAnalysisMaterials" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteTaskAnalysisId" integer NOT NULL,
        "VendorProductId" integer,
        "SortOrder" integer NOT NULL,
        "VendorSku" character varying(100),
        "Description" character varying(500) NOT NULL,
        "Quantity" numeric(18,4) NOT NULL,
        "Unit" character varying(40) NOT NULL,
        "UnitCost" numeric(18,4) NOT NULL,
        "WastePercent" numeric(8,4) NOT NULL,
        "MatchConfidence" numeric(5,4) NOT NULL,
        "SourceType" character varying(100),
        "SourceReference" character varying(255),
        "SourcePriceDate" date,
        "IsUnmatched" boolean NOT NULL,
        "Notes" character varying(1000),
        CONSTRAINT "PK_QuoteTaskAnalysisMaterials" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteTaskAnalysisMaterials_QuoteTaskAnalyses_QuoteTaskAnaly~" FOREIGN KEY ("QuoteTaskAnalysisId") REFERENCES "QuoteTaskAnalyses" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_QuoteTaskAnalysisMaterials_VendorProducts_VendorProductId" FOREIGN KEY ("VendorProductId") REFERENCES "VendorProducts" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729163041_AddCentComTaskAnalysis') THEN
    CREATE UNIQUE INDEX "IX_QuoteTaskAnalyses_QuoteProjectTaskId_RevisionNumber" ON "QuoteTaskAnalyses" ("QuoteProjectTaskId", "RevisionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729163041_AddCentComTaskAnalysis') THEN
    CREATE UNIQUE INDEX "IX_QuoteTaskAnalysisMaterials_QuoteTaskAnalysisId_SortOrder" ON "QuoteTaskAnalysisMaterials" ("QuoteTaskAnalysisId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729163041_AddCentComTaskAnalysis') THEN
    CREATE INDEX "IX_QuoteTaskAnalysisMaterials_VendorProductId" ON "QuoteTaskAnalysisMaterials" ("VendorProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729163041_AddCentComTaskAnalysis') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260729163041_AddCentComTaskAnalysis', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    ALTER TABLE "QuoteProjectTasks" ADD "ContingencyPercentOverride" numeric(8,4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    ALTER TABLE "QuoteProjectTasks" ADD "CrewSizeOverride" numeric(8,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    ALTER TABLE "QuoteProjectTasks" ADD "DailyCrewCostOverride" numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    ALTER TABLE "QuoteProjectTasks" ADD "EstimatedDays" numeric(8,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    ALTER TABLE "QuoteProjectTasks" ADD "TargetMarginPercentOverride" numeric(8,4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE TABLE "CostingPolicyVersions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LocalOperationId" integer,
        "Name" character varying(120) NOT NULL,
        "RevisionNumber" integer NOT NULL,
        "EffectiveDate" date NOT NULL,
        "EndDate" date,
        "IsActive" boolean NOT NULL,
        "DefaultDailyCrewCost" numeric(18,2) NOT NULL,
        "DefaultCrewSize" numeric(8,2) NOT NULL,
        "DefaultContingencyPercent" numeric(8,4) NOT NULL,
        "DefaultTargetMarginPercent" numeric(8,4) NOT NULL,
        "GeneralOverheadFixed" numeric(18,2) NOT NULL,
        "GeneralOverheadPerProjectDay" numeric(18,2) NOT NULL,
        "GeneralOverheadPercent" numeric(8,4) NOT NULL,
        "Notes" character varying(1000),
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" character varying(450),
        CONSTRAINT "PK_CostingPolicyVersions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CostingPolicyVersions_LocalOperations_LocalOperationId" FOREIGN KEY ("LocalOperationId") REFERENCES "LocalOperations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE TABLE "CostingPolicyRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CostingPolicyVersionId" integer NOT NULL,
        "Name" character varying(120) NOT NULL,
        "Scope" character varying(20) NOT NULL,
        "TaskType" character varying(100),
        "CalculationMethod" character varying(40) NOT NULL,
        "Rate" numeric(18,4) NOT NULL,
        "IsActive" boolean NOT NULL,
        "Notes" character varying(500),
        CONSTRAINT "PK_CostingPolicyRules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CostingPolicyRules_CostingPolicyVersions_CostingPolicyVersi~" FOREIGN KEY ("CostingPolicyVersionId") REFERENCES "CostingPolicyVersions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE TABLE "QuoteCostSnapshots" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteVersionId" integer NOT NULL,
        "CostingPolicyVersionId" integer NOT NULL,
        "RevisionNumber" integer NOT NULL,
        "PricedAt" timestamp with time zone NOT NULL,
        "PricedByUserId" character varying(450),
        "DirectCost" numeric(18,2) NOT NULL,
        "ProjectOverhead" numeric(18,2) NOT NULL,
        "Contingency" numeric(18,2) NOT NULL,
        "TotalCost" numeric(18,2) NOT NULL,
        "TargetMarginPercent" numeric(8,4) NOT NULL,
        "SuggestedCustomerPrice" numeric(18,2) NOT NULL,
        "PriceAdjustment" numeric(18,2) NOT NULL,
        "AdjustmentReason" character varying(1000),
        CONSTRAINT "PK_QuoteCostSnapshots" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteCostSnapshots_CostingPolicyVersions_CostingPolicyVersi~" FOREIGN KEY ("CostingPolicyVersionId") REFERENCES "CostingPolicyVersions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_QuoteCostSnapshots_QuoteVersions_QuoteVersionId" FOREIGN KEY ("QuoteVersionId") REFERENCES "QuoteVersions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE TABLE "QuoteTaskCostSnapshots" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteCostSnapshotId" integer NOT NULL,
        "QuoteProjectTaskId" integer NOT NULL,
        "MaterialCost" numeric(18,2) NOT NULL,
        "EstimatedDays" numeric(8,2) NOT NULL,
        "CrewSize" numeric(8,2) NOT NULL,
        "DailyCrewCost" numeric(18,2) NOT NULL,
        "LaborCost" numeric(18,2) NOT NULL,
        "TaskOverhead" numeric(18,2) NOT NULL,
        "Contingency" numeric(18,2) NOT NULL,
        "TotalCost" numeric(18,2) NOT NULL,
        "AppliedRules" character varying(2000),
        CONSTRAINT "PK_QuoteTaskCostSnapshots" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteTaskCostSnapshots_QuoteCostSnapshots_QuoteCostSnapshot~" FOREIGN KEY ("QuoteCostSnapshotId") REFERENCES "QuoteCostSnapshots" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_QuoteTaskCostSnapshots_QuoteProjectTasks_QuoteProjectTaskId" FOREIGN KEY ("QuoteProjectTaskId") REFERENCES "QuoteProjectTasks" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE INDEX "IX_CostingPolicyRules_CostingPolicyVersionId" ON "CostingPolicyRules" ("CostingPolicyVersionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE UNIQUE INDEX "IX_CostingPolicyVersions_LocalOperationId_Name_RevisionNumber" ON "CostingPolicyVersions" ("LocalOperationId", "Name", "RevisionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE INDEX "IX_QuoteCostSnapshots_CostingPolicyVersionId" ON "QuoteCostSnapshots" ("CostingPolicyVersionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE UNIQUE INDEX "IX_QuoteCostSnapshots_QuoteVersionId_RevisionNumber" ON "QuoteCostSnapshots" ("QuoteVersionId", "RevisionNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE INDEX "IX_QuoteTaskCostSnapshots_QuoteCostSnapshotId" ON "QuoteTaskCostSnapshots" ("QuoteCostSnapshotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    CREATE INDEX "IX_QuoteTaskCostSnapshots_QuoteProjectTaskId" ON "QuoteTaskCostSnapshots" ("QuoteProjectTaskId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260729203110_AddVersionedCostingPolicies') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260729203110_AddVersionedCostingPolicies', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730141002_AddMaterialExclusionRules') THEN
    CREATE TABLE "MaterialExclusionRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MatchPhrase" character varying(200) NOT NULL,
        "TaskType" character varying(100),
        "Reason" character varying(500) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" character varying(450),
        CONSTRAINT "PK_MaterialExclusionRules" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730141002_AddMaterialExclusionRules') THEN
    CREATE TABLE "QuoteTaskAnalysisExclusions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteTaskAnalysisId" integer NOT NULL,
        "MaterialExclusionRuleId" integer NOT NULL,
        "Description" character varying(500) NOT NULL,
        "Reason" character varying(500) NOT NULL,
        "ExcludedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_QuoteTaskAnalysisExclusions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteTaskAnalysisExclusions_MaterialExclusionRules_Material~" FOREIGN KEY ("MaterialExclusionRuleId") REFERENCES "MaterialExclusionRules" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_QuoteTaskAnalysisExclusions_QuoteTaskAnalyses_QuoteTaskAnal~" FOREIGN KEY ("QuoteTaskAnalysisId") REFERENCES "QuoteTaskAnalyses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730141002_AddMaterialExclusionRules') THEN
    CREATE UNIQUE INDEX "IX_MaterialExclusionRules_MatchPhrase_TaskType" ON "MaterialExclusionRules" ("MatchPhrase", "TaskType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730141002_AddMaterialExclusionRules') THEN
    CREATE INDEX "IX_QuoteTaskAnalysisExclusions_MaterialExclusionRuleId" ON "QuoteTaskAnalysisExclusions" ("MaterialExclusionRuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730141002_AddMaterialExclusionRules') THEN
    CREATE INDEX "IX_QuoteTaskAnalysisExclusions_QuoteTaskAnalysisId" ON "QuoteTaskAnalysisExclusions" ("QuoteTaskAnalysisId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730141002_AddMaterialExclusionRules') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730141002_AddMaterialExclusionRules', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    ALTER TABLE "QuoteTaskCostSnapshots" ADD "AllocatedProjectOverhead" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    ALTER TABLE "QuoteTaskCostSnapshots" ADD "RequiredSupplyCost" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    ALTER TABLE "QuoteTaskCostSnapshots" ADD "SuggestedCustomerPrice" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    ALTER TABLE "QuoteTaskCostSnapshots" ADD "TargetMarginPercent" numeric(8,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    ALTER TABLE "QuoteProjectTasks" ADD "WorkType" character varying(60);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    ALTER TABLE "MaterialExclusionRules" ADD "RecoveryReference" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    ALTER TABLE "MaterialExclusionRules" ADD "RecoveryType" character varying(60);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    ALTER TABLE "CostingPolicyVersions" ADD "ExpectedMonthlyProductiveCrewDays" numeric(8,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    ALTER TABLE "CostingPolicyVersions" ADD "MonthlyOverheadBudget" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE TABLE "CrewRateCards" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CostingPolicyVersionId" integer NOT NULL,
        "TaskType" character varying(100) NOT NULL,
        "WorkType" character varying(60),
        "CrewSize" numeric(8,2) NOT NULL,
        "DailyCrewCost" numeric(18,2) NOT NULL,
        "IsActive" boolean NOT NULL,
        "Notes" character varying(500),
        CONSTRAINT "PK_CrewRateCards" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CrewRateCards_CostingPolicyVersions_CostingPolicyVersionId" FOREIGN KEY ("CostingPolicyVersionId") REFERENCES "CostingPolicyVersions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE TABLE "QuoteTaskSupplyCostSnapshots" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuoteTaskCostSnapshotId" integer NOT NULL,
        "VendorProductId" integer,
        "KitName" character varying(120) NOT NULL,
        "Description" character varying(300) NOT NULL,
        "Quantity" numeric(18,4) NOT NULL,
        "UnitCost" numeric(18,4) NOT NULL,
        "WastePercent" numeric(8,4) NOT NULL,
        "ExtendedCost" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_QuoteTaskSupplyCostSnapshots" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuoteTaskSupplyCostSnapshots_QuoteTaskCostSnapshots_QuoteTa~" FOREIGN KEY ("QuoteTaskCostSnapshotId") REFERENCES "QuoteTaskCostSnapshots" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_QuoteTaskSupplyCostSnapshots_VendorProducts_VendorProductId" FOREIGN KEY ("VendorProductId") REFERENCES "VendorProducts" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE TABLE "StandardSupplyKits" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CostingPolicyVersionId" integer NOT NULL,
        "Name" character varying(120) NOT NULL,
        "TaskType" character varying(100),
        "WorkType" character varying(60),
        "IsActive" boolean NOT NULL,
        "Notes" character varying(500),
        CONSTRAINT "PK_StandardSupplyKits" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StandardSupplyKits_CostingPolicyVersions_CostingPolicyVersi~" FOREIGN KEY ("CostingPolicyVersionId") REFERENCES "CostingPolicyVersions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE TABLE "TaskMarginRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CostingPolicyVersionId" integer NOT NULL,
        "TaskType" character varying(100) NOT NULL,
        "WorkType" character varying(60),
        "TargetMarginPercent" numeric(8,4) NOT NULL,
        "IsActive" boolean NOT NULL,
        "Notes" character varying(500),
        CONSTRAINT "PK_TaskMarginRules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TaskMarginRules_CostingPolicyVersions_CostingPolicyVersionId" FOREIGN KEY ("CostingPolicyVersionId") REFERENCES "CostingPolicyVersions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE TABLE "StandardSupplyKitItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StandardSupplyKitId" integer NOT NULL,
        "VendorProductId" integer NOT NULL,
        "Quantity" numeric(18,4) NOT NULL,
        "WastePercent" numeric(8,4) NOT NULL,
        "Notes" character varying(500),
        CONSTRAINT "PK_StandardSupplyKitItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StandardSupplyKitItems_StandardSupplyKits_StandardSupplyKit~" FOREIGN KEY ("StandardSupplyKitId") REFERENCES "StandardSupplyKits" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StandardSupplyKitItems_VendorProducts_VendorProductId" FOREIGN KEY ("VendorProductId") REFERENCES "VendorProducts" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE UNIQUE INDEX "IX_CrewRateCards_CostingPolicyVersionId_TaskType_WorkType" ON "CrewRateCards" ("CostingPolicyVersionId", "TaskType", "WorkType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE INDEX "IX_QuoteTaskSupplyCostSnapshots_QuoteTaskCostSnapshotId" ON "QuoteTaskSupplyCostSnapshots" ("QuoteTaskCostSnapshotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE INDEX "IX_QuoteTaskSupplyCostSnapshots_VendorProductId" ON "QuoteTaskSupplyCostSnapshots" ("VendorProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE UNIQUE INDEX "IX_StandardSupplyKitItems_StandardSupplyKitId_VendorProductId" ON "StandardSupplyKitItems" ("StandardSupplyKitId", "VendorProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE INDEX "IX_StandardSupplyKitItems_VendorProductId" ON "StandardSupplyKitItems" ("VendorProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE UNIQUE INDEX "IX_StandardSupplyKits_CostingPolicyVersionId_Name" ON "StandardSupplyKits" ("CostingPolicyVersionId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    CREATE UNIQUE INDEX "IX_TaskMarginRules_CostingPolicyVersionId_TaskType_WorkType" ON "TaskMarginRules" ("CostingPolicyVersionId", "TaskType", "WorkType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730152604_AddLayeredCostingModel') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730152604_AddLayeredCostingModel', '10.0.9');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731190846_AddMaterialCatalogFallbackReview') THEN
    ALTER TABLE "QuoteTaskAnalysisMaterials" ADD "IsRemoved" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731190846_AddMaterialCatalogFallbackReview') THEN
    ALTER TABLE "QuoteTaskAnalysisMaterials" ADD "MatchKind" character varying(30) NOT NULL DEFAULT 'Catalog';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731190846_AddMaterialCatalogFallbackReview') THEN
    ALTER TABLE "QuoteTaskAnalysisMaterials" ADD "OriginalDescription" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731190846_AddMaterialCatalogFallbackReview') THEN
    ALTER TABLE "QuoteTaskAnalysisMaterials" ADD "ReviewDecision" character varying(30) NOT NULL DEFAULT 'Accepted';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731190846_AddMaterialCatalogFallbackReview') THEN
    UPDATE "QuoteTaskAnalysisMaterials"
    SET "OriginalDescription" = "Description",
        "MatchKind" = CASE WHEN "IsUnmatched" THEN 'Unresolved' ELSE 'Catalog' END,
        "ReviewDecision" = CASE WHEN "IsUnmatched" THEN 'Pending' ELSE 'Accepted' END;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260731190846_AddMaterialCatalogFallbackReview') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260731190846_AddMaterialCatalogFallbackReview', '10.0.9');
    END IF;
END $EF$;
COMMIT;

